---
layout: page
title: Readings
description: List of readings
output:
  md_document:
    variant: markdown_github
    preserve_yaml: true
---


```{r, echo=FALSE}
# Options
knitr::opts_chunk$set(message = FALSE) # Ensures that no messages show up
knitr::opts_chunk$set(echo = FALSE) # Ensures that no echo show up

# Bib file
biblio = bibtex::read.bib("~/Dropbox/BibLibrary.bib")

# A small function to shorten the command for bib references
ref = function(key) {
capture.output(print(biblio[key])) # This would be the way to print the ref
}

```

# Readings

Below is a non-exhaustive (though pretty long) list of readings. 

<br/>

## Growth models and persistance

`r ref("Cominetal2010")`

`r ref("Dell2010")`

`r ref("MiguelRoland2011")`

`r ref("Hornbeck2012")`

`r ref("VoigtlanderVoth2012")`

`r ref("Guisoetal2016")`

`r ref("Dalgaardetal2018")`

*Background reading:*
  
`r ref("kelly2019standard")`

## Capital, investments, and firms

`r ref("Gray2013")`

`r ref("jensen2017job")`

`r ref("Samila:2017aa")`

`r ref("danzman2019merging")`

`r ref("jensen2020electoral")`

*Background reading:*
  
`r ref("Coase1937")`

`r ref("edwards1995saving")`

`r ref("mellahi2016review")`

## Labor, migration, and unions

`r ref("franzen2006social")`

`r ref("hayashi2008depressing")`

`r ref("HainmuellerHicox2010")`

`r ref("hainmueller2013gets")`

`r ref("Jansenetal2016")`

`r ref("frymer2021labor")`

`r ref("bouscasse2021did")`

`r ref("Erikson:2021aa")`

`r ref("lim2022electoral")`

`r ref("jones2022end")`

*Background reading:*
  
`r ref("Jageretal2022")`

`r ref("Naidu2022")`

## Land and agriculture

`r ref("heldring2021long")`

`r ref("finley2021free")`

`r ref("Chang2022")`

*Background reading:*
  
`r ref("johnston1961role")`

`r ref("moore1966")`

`r ref("byerlee2009agriculture")`


## Technology and the backlash against globalization

`r ref("AcemogluRestrepo2020")`

`r ref("Owen2020")`

`r ref("BusemeyerTober2022")`

`r ref("Limetal2022")`

*Background reading:*
  
`r ref("Schumpeter1934")`

`r ref("iversen2001asset")`

`r ref("walter2021backlash")`


## Human capital

`r ref("Stijns2006")`

`r ref("HardingStasavage2013")`

`r ref("ansell2013political")`

`r ref("CantoniYuchtman2014")`

`r ref("SquicciariniVoigtlander2015")`

`r ref("Rauscher2016")`

`r ref("Crokeetal2016")`

`r ref("de2018clans")`

`r ref("squicciarini2020devotion")`

*Background reading:*
  
`r ref("Barro2001")`

`r ref("GoldinKatz2010")`

## Social capital and networks

`r ref("Satyanathetal2017")`

`r ref("frank2018small")`

`r ref("hong2020universal")`

*Background reading:*
  
`r ref("montgomery1991social")`

`r ref("Putnam2001")`

`r ref("glaeser2008cities")`

## Institutions, democray, and autocracy

`r ref("FeyrerSacerdote2009")`

`r ref("MichalopoulosPapaioannou2013")`

`r ref("Fernandez2014")`

`r ref("Pepinsky2016")`

`r ref("Lacroix2017")`

`r ref("Acemogluetal2019")`

*Background reading:*
  
`r ref("Lipset1959")`

`r ref("odonnell1973modernization")`

`r ref("Dahl1989")`

`r ref("przeworski1991democracy")`

`r ref("Acemogluetal2001")`

`r ref("BaumLake2003")`

`r ref("rodrik2004institutions")`

`r ref("Glaeseretal2004")`

`r ref("Cheibubetal2010")`

`r ref("acemoglu2021institutional")`

## Institutions: autocracies

`r ref("Albertus2015")`

`r ref("Miller2015")`

`r ref("Geddesetal2018")`

`r ref("Doweretal2018")`

`r ref("RozenasZuhukov2019")`

`r ref("RizioSkali2019")`

`r ref("Chang2022")`

*Background reading:*
  
`r ref("linz2000totalitarian")`

`r ref("Olson1993")`

`r ref("Gandhi2008")`

`r ref("Svolik2012")`

`r ref("Gehlbachetal2016")`

## Institutions, bureaucracy, and state capacity

`r ref("acemoglu2015state")`

`r ref("vogler2019imperial")`

`r ref("colonnelli2020patronage")`

`r ref("rich2022outsourcing")`

`r ref("Slough2022")`

*Background reading:*
  
`r ref("Weber2019")`
`
`r ref("hendrix2010measuring")`

`r ref("pomeranz2019taking")`

`r ref("besley2022bureaucracy")`

## Informal institutions

`r ref("Tsai2006")`

`r ref("Alesinaetal2013")`

`r ref("Cantoni2015")`

`r ref("Nowaketal2016")`

`r ref("Schulz2017")`

`r ref("Lowesetal2017")`

`r ref("Lehne2018")`

*Background reading:*
  
`r ref("BourdieuPasseron1990")`

`r ref("Mauss2000")`

`r ref("Lauth2000")`

`r ref("Guisoetal2006")`

`r ref("AlesinaGuiliano2015")`

## Law, crime, and property rights


`r ref("KosterlnikSkarbek2013")`

`r ref("Dubeetal2016")`

`r ref("Dimicoetal2017")`

`r ref("daniele2022fighting")`

*Background reading:*
  
`r ref("Anderson1965")`

`r ref("NorthWeingast1989")`

`r ref("GottfredsonHirschi1990")`

`r ref("FiorentiniPeltzman1997")`

`r ref("LaPortaetal2008")`

`r ref("Venkatesh2008")`

## Violence and war

`r ref("nunn2011slave")`

`r ref("berger2013commercial")`

`r ref("Oatley2015")`

`r ref("braun2016religious")`

`r ref("Kloretal2017")`

`r ref("DellQuerubin2017")`

`r ref("LeesonRuss2017")`

`r ref("Feibenbaumetal2018")`

`r ref("CoxDincecco2019")`

*Background reading:*
  
`r ref("tilly2017war")`

## Agency and leadership

`r ref("LiZhou2005")`

`r ref("JonesOlken2005")`

`r ref("KhwajaMian2005")`

`r ref("Faccio2006")`

`r ref("FergusonVoth2008")`

`r ref("QuerubinSnyder2013")`

`r ref("DalBoetal2017")`

`r ref("GirardiBowles2018")`

`r ref("ChenKaising2018")`

`r ref("Thompsonetal2019")`

`r ref("EasterlyPennings2020")`

`r ref("carreri2021can")`

`r ref("mehmood2021training")`

## Trade

`r ref("rho2017don")`

`r ref("Juhasz2018")`

`r ref("barjamovic2019trade")`

*Background reading:*
  
`r ref("Greif1993")`

`r ref("MilnerKubota2005")`

`r ref("SpolaoreWacziarg2009")`

`r ref("HarrisonRodriguezClare2009")`

`r ref("Hays2009")`

## Fiscal policy

`r ref("Dincecco2010")`

`r ref("pickering2011ideology")`

`r ref("RaessPontusson2015")`

`r ref("ScheveStasavage2016")`

`r ref("BenedictisWarshaw2016")`

`r ref("BodeaHigashijima2017")`

`r ref("HuebscherSattler2017")`

`r ref("Rickard2018")`

`r ref("andersson_2022")`

*Background reading:*
  
`r ref("levi1988rule")`

`r ref("alt1994divided")`

## Inequality

`r ref("Acemogluetal2021")`

`r ref("acemoglu2022tasks")`

`r ref("lindgren_oskarsson_2022")`

*Background reading:*
  
`r ref("MoeneWallerstein2001")`

`r ref("KenworthyPontusson2005")`

`r ref("Piketty2013")`

`r ref("BlanchardRodrik2021")`

## Money, credit, and debt

`r ref("Fahlenbrachetal2012")`

`r ref("SchularickTaylor2012")`

`r ref("McCartyetal2013")`

`r ref("CalomirisHaber2014")`

`r ref("ReinhartRogoff2014")`

`r ref("mcdowell2017brother")`

`r ref("Lipscy2018")`

`r ref("CopelovitchSinger2020")`

*Background reading:*
  
`r ref("Satyanath2005")`

`r ref("Frieden2007")`

`r ref("Broz2009")`

`r ref("ReinhartRogoff2009")`

`r ref("Stasavage2011")`






