---
output: 
  pdf_document:
    keep_tex: false
    keep_md: false
    fig_caption: yes
    latex_engine: pdflatex
    template: ~/Dropbox/Teaching/svm-latex-syllabus.tex
geometry: margin=1in
title: "Political Economy of Growth (PS 2543)"
author: Michaël Aklin
email: "aklin@pitt.edu"
web: "michaelaklin.github.io"
officehours: "TBD"
office: "TBD"
classroom: "4430 Posvar"
classhours: "12-2:30"
fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2023-01-09")
#mon <- as.Date("2021-01-25")
# fri <- as.Date("2016-01-08")
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon)
# tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}


# Bib file
biblio = bibtex::read.bib("~/Dropbox/BibLibrary.bib")

# A small function to shorten the command for bib references
ref = function(key) {
#  print(biblio[key])
    capture.output(biblio[key])
# capture.output(print(biblio[key])) # This would be the way to print the ref
}

```


# Course Objectives

This graduate course is devoted to the study of the politics of economic growth. While this is nominally a course at the intersection of IPE and CPE, you will see that it borrows heavily from other subfields and disciplines (primarily econonomics, but also public policy, management, history, sociology, etc.).

The aim for this course is:

- to ensure that you have a strong overview of theoretical models of growth

- to show the richness of rigorous empirical work that has been conducted

- to stimulate new research ideas, new theories, and novel empirical designs

Note: the course is primarily one based on presentations and discussions. The readings consists in a mix of 'classics' and recent papers. The latter were selected because they are either interesting (if I read them) or they seem interesting (based on the abstract). 

# Requirements

**Assignments**. 

- 50%: a research project/pre-analysis plan (including theory + empirical design; data analysis optional) 

- 40%: in-class presentations and participation. 

- 10%: a book review. 

**Grade scale**: 0 < 60: F, 60 < 64: D-, 64 < 67: D, 67 < 70: D+, 70 < 73: C-, 74 < 77: C, 77 < 80: C+, 80 < 84: B-, 84 < 87: B, 87 < 90: B+, 90 < 94: A-, 93 or more: A. "Y < X" means: "from Y up to, but not including X." Grades are not rounded up.

**Late submissions** are penalized by a loss of 2 percentage points per day. If you have issues that prevent you from submitting an assignment on time, then please let me know immediately. If you inform me _after_ a deadline has passed, I will need to be provided justification (e.g. doctor's note) to cancel the late submission penalty. 

**Important note**: you can discuss ideas with your fellow students, but you must do your assignments individually. For pedagogical reasons, it is essential that you must try to understand the material on your own.

# Organization

Every course is divided in three parts:

1. Lecture (if applicable)

2. Paper presentation (+ discussion)

3. Project presentation

# Readings

There are no required textbooks for this class. Useful textbooks to study growth models include:

\bigskip

* `r ref("aghion2008economics")`

* `r ref("Acemoglu2009")`


<!-- \bigskip -->

<!-- The following books and papers are classics that you might want to be familiar with. You do *not* need to buy them. Draw inspiration from them. -->

<!-- \bigskip -->

<!-- * `r ref("Schumpeter1934")` -->

<!-- * `r ref("Hirschman1970")` -->

<!-- * `r ref("Ostrom1990")` -->

<!-- * `r ref("North1991")` -->

<!-- * `r ref("Tilly1992")` -->

<!-- * `r ref("Sen1999")` -->

<!-- * `r ref("Przeworskietal2000")` -->

<!-- * `r ref("Polanyi2001")` -->

<!-- * `r ref("Weber2002")` -->

<!-- * `r ref("Easterly2007")` -->

<!-- * `r ref("Tocqueville2008")` -->

<!-- * `r ref("BanerjeeDuflo2012")` -->

<!-- * `r ref("Strange2015")` -->

<!-- * `r ref("Eichengreen2019")` -->

\newpage

# Class Schedule

<!-- Other topics:
- Corruption
- Non-market strategies (interest groups, rent-seeking) (Jensen, etc)
-->

The schedule is subject to change. 

## \textcolor{darkblue}{`r advdate(mon, 1)`: Introduction}

`r ref("HallJones1999")`

`r ref("Galor2005")`


<!-- *Background reading:* -->

<!-- ```{r, echo = FALSE, results="asis"}  -->
<!-- bib["bouscasse2021did"] -->
<!-- ```  -->


\bigskip

## \textcolor{darkblue}{`r advdate(mon, 2)`: MLK Day}

No class.

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 3)`: Growth models and persistance}

`r ref("Cominetal2010")`

`r ref("Dell2010")`

`r ref("MiguelRoland2011")`

`r ref("Hornbeck2012")`

`r ref("VoigtlanderVoth2012")`

`r ref("Guisoetal2016")`

`r ref("Dalgaardetal2018")`

`r ref("fouka2022collective")`

\bigskip

*Background reading:*
  
`r ref("kelly2019standard")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 4)`: Capital, investments, and firms}

<!-- capital, investments, savings, non-market strategies -->


`r ref("Gray2013")`

`r ref("jensen2017job")`

`r ref("Samila:2017aa")`

`r ref("danzman2019merging")`

`r ref("jensen2020electoral")`

\bigskip

*Background reading:*
  
`r ref("Coase1937")`

`r ref("edwards1995saving")`

`r ref("mellahi2016review")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 5)`: Labor, migration, and unions}

`r ref("Jansenetal2016")`

`r ref("frymer2021labor")`

`r ref("bouscasse2021did")`

`r ref("Erikson:2021aa")`

`r ref("lim2022electoral")`

`r ref("jones2022end")`

`r ref("colonnelli2022politics")`

\bigskip

*Background reading:*

`r ref("franzen2006social")`

`r ref("hayashi2008depressing")`

`r ref("HainmuellerHicox2010")`

`r ref("hainmueller2013gets")`
  
`r ref("Jageretal2022")`

`r ref("Naidu2022")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 6)`: Land and agriculture}

`r ref("heldring2021long")`

`r ref("finley2021free")`

`r ref("Chang2022")`

\bigskip

*Background reading:*
  
`r ref("johnston1961role")`

`r ref("moore1966")`

`r ref("byerlee2009agriculture")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 7)`: Technology and infrastructure}

<!-- Automation -->

`r ref("hornung2014immigration")`

`r ref("AcemogluRestrepo2020")`

`r ref("Owen2020")`

`r ref("BusemeyerTober2022")`

`r ref("Limetal2022")`

`r ref("braun_franke_2022")`

`r ref("voth2022fighting")`

\bigskip

*Background reading:*
  
`r ref("Schumpeter1934")`

`r ref("iversen2001asset")`

`r ref("walter2021backlash")`

\bigskip


## \textcolor{darkblue}{`r advdate(mon, 8)`: Human capital}

`r ref("Stijns2006")`

`r ref("HardingStasavage2013")`

`r ref("ansell2013political")`

`r ref("CantoniYuchtman2014")`

`r ref("SquicciariniVoigtlander2015")`

`r ref("Rauscher2016")`

`r ref("Crokeetal2016")`

`r ref("de2018clans")`

`r ref("squicciarini2020devotion")`

\bigskip

*Background reading:*

`r ref("BourdieuPasseron1990")`
  
`r ref("weitzman1998recombinant")`

`r ref("Barro2001")`

`r ref("GoldinKatz2010")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 8)`: Social capital and networks}

`r ref("Satyanathetal2017")`

`r ref("frank2018small")`

`r ref("hong2020universal")`

\bigskip

*Background reading:*
  
`r ref("montgomery1991social")`

`r ref("Putnam2001")`

`r ref("glaeser2008cities")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 9)`: Spring Break}

No class.

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 10)`: Institutions (democracy vs autocracy)}


`r ref("FeyrerSacerdote2009")`

`r ref("MichalopoulosPapaioannou2013")`

`r ref("Fernandez2014")`

`r ref("Pepinsky2016")`

`r ref("Lacroix2017")`

`r ref("Acemogluetal2019")`

\bigskip

*Background reading:*
  
`r ref("Lipset1959")`

`r ref("odonnell1973modernization")`

`r ref("Dahl1989")`

`r ref("przeworski1991democracy")`

`r ref("Acemogluetal2001")`

`r ref("BaumLake2003")`

`r ref("rodrik2004institutions")`

`r ref("Glaeseretal2004")`

`r ref("Cheibubetal2010")`

`r ref("acemoglu2021institutional")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 11)`: Institutions (autocracy)}

`r ref("Albertus2015")`

`r ref("Miller2015")`

`r ref("Geddesetal2018")`

`r ref("Doweretal2018")`

`r ref("RozenasZuhukov2019")`

`r ref("RizioSkali2019")`

`r ref("Chang2022")`

\bigskip

*Background reading:*
  
`r ref("linz2000totalitarian")`

`r ref("Olson1993")`

`r ref("Gandhi2008")`

`r ref("Svolik2012")`

`r ref("Gehlbachetal2016")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 12)`: Institutions (bureaucracy, state capacity)}

`r ref("acemoglu2015state")`

`r ref("vogler2019imperial")`

`r ref("colonnelli2020patronage")`

`r ref("rich2022outsourcing")`

`r ref("Slough2022")`

\bigskip

*Background reading:*
  
`r ref("Weber2019")`
`
`r ref("hendrix2010measuring")`

`r ref("pomeranz2019taking")`

`r ref("besley2022bureaucracy")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 13)`: Institutions (informal)}

`r ref("Tsai2006")`

`r ref("Alesinaetal2013")`

`r ref("Cantoni2015")`

`r ref("Nowaketal2016")`

`r ref("Schulz2017")`

`r ref("Lowesetal2017")`

`r ref("Lehne2018")`

\bigskip

*Background reading:*
  
`r ref("BourdieuPasseron1990")`

`r ref("Mauss2000")`

`r ref("Lauth2000")`

`r ref("Guisoetal2006")`

`r ref("AlesinaGuiliano2015")`

\bigskip

##  \textcolor{darkblue}{`r advdate(mon, 14)`: Law, crime, and property rights}

`r ref("KosterlnikSkarbek2013")`

`r ref("Dubeetal2016")`

`r ref("Dimicoetal2017")`

`r ref("daniele2022fighting")`

`r ref("ash2022ideas")`

\bigskip

*Background reading:*
  
`r ref("Anderson1965")`

`r ref("krueger1974political")`

`r ref("NorthWeingast1989")`

`r ref("GottfredsonHirschi1990")`

`r ref("FiorentiniPeltzman1997")`

`r ref("LaPortaetal2008")`

`r ref("Venkatesh2008")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 15)`: Violence and war}

`r ref("nunn2011slave")`

`r ref("berger2013commercial")`

`r ref("Oatley2015")`

`r ref("braun2016religious")`

`r ref("Kloretal2017")`

`r ref("DellQuerubin2017")`

`r ref("LeesonRuss2017")`

`r ref("Feibenbaumetal2018")`

`r ref("Feibenbaumetal2018")`

`r ref("CoxDincecco2019")`

`r ref("hager2022does")`

`r ref("Bachmannetal2022")`

\bigskip

*Background reading:*
  
`r ref("tilly2017war")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 16)`: Agency and leadership}

`r ref("LiZhou2005")`

`r ref("JonesOlken2005")`

`r ref("KhwajaMian2005")`

`r ref("Faccio2006")`

`r ref("FergusonVoth2008")`

`r ref("QuerubinSnyder2013")`

`r ref("DalBoetal2017")`

`r ref("GirardiBowles2018")`

`r ref("ChenKaising2018")`

`r ref("Thompsonetal2019")`

`r ref("EasterlyPennings2020")`

`r ref("carreri2021can")`

`r ref("mehmood2021training")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 17)`: Trade}

`r ref("rho2017don")`

`r ref("Juhasz2018")`

`r ref("barjamovic2019trade")`

\bigskip

*Background reading:*
  
`r ref("Greif1993")`

`r ref("MilnerKubota2005")`

`r ref("SpolaoreWacziarg2009")`

`r ref("HarrisonRodriguezClare2009")`

`r ref("Hays2009")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 18)`: Fiscal policy}

`r ref("Dincecco2010")`

`r ref("pickering2011ideology")`

`r ref("RaessPontusson2015")`

`r ref("ScheveStasavage2016")`

`r ref("BenedictisWarshaw2016")`

`r ref("BodeaHigashijima2017")`

`r ref("HuebscherSattler2017")`

`r ref("Rickard2018")`

`r ref("andersson_2022")`

\bigskip

*Background reading:*
  
`r ref("levi1988rule")`

`r ref("alt1994divided")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 19)`: Models of inequality}

`r ref("Acemogluetal2021")`

`r ref("acemoglu2022tasks")`

`r ref("lindgren_oskarsson_2022")`

\bigskip

*Background reading:*
  
`r ref("MoeneWallerstein2001")`

`r ref("KenworthyPontusson2005")`

`r ref("Piketty2013")`

`r ref("BlanchardRodrik2021")`

\bigskip

## \textcolor{darkblue}{`r advdate(mon, 19)`: Money, credit, and debt}

`r ref("Fahlenbrachetal2012")`

`r ref("SchularickTaylor2012")`

`r ref("McCartyetal2013")`

`r ref("CalomirisHaber2014")`

`r ref("ReinhartRogoff2014")`

`r ref("mcdowell2017brother")`

`r ref("Lipscy2018")`

`r ref("CopelovitchSinger2020")`

\bigskip

*Background reading:*
  
`r ref("Satyanath2005")`

`r ref("Frieden2007")`

`r ref("Broz2009")`

`r ref("ReinhartRogoff2009")`

`r ref("Stasavage2011")`

## \textcolor{darkblue}{`r advdate(mon, 19)`: Culture}

`r ref("Grosfeldetal2013")`

`r ref("Lowesetal2017")`

`r ref("MichalopoulosXue2021")`

\bigskip

*Background reading:*

`r ref("AlesinaGuiliano2015")`


\newpage


# Course policies

## Pandemic/COVID

During this pandemic, it is extremely important that you abide by the public health regulations, the University of Pittsburgh’s health standards and guidelines, and Pitt's Health Rules. These rules have been developed to protect the health and safety of all of us.  Universal face covering is required in all classrooms and in every building on campus, without exceptions, regardless of vaccination status. This means you must wear a face covering that properly covers your nose and mouth when you are in the classroom. If you do not comply, you will be asked to leave class.  It is your responsibility have the required face covering when entering a university building or classroom. For the most up-to-date information and guidance, please visit https://coronavirus.pitt.edu and check your Pitt email for updates before each class.

If you are required to isolate or quarantine, become sick, or are unable to come to class, contact me as soon as possible to discuss arrangements.

## Disability Resource Services

If you have a disability for which you are or may be requesting an accommodation, you are encouraged to contact both your instructor and the Office of Disability Resources and Services, 140 William Pitt Union, 412-648-7890, as early as possible in the term. Disability Resources and Services will verify your disability and determine reasonable accommodations for this course.

## Academic Integrity Policy 

Cheating/plagiarism will not be tolerated. Students suspected of violating the University of Pittsburgh Policy on Academic Integrity, noted below, will be required to participate in the outlined procedural process as initiated by the instructor. A minimum sanction of a zero score for the quiz, exam or paper will be imposed. (For the full Academic Integrity policy, go to www.provost.pitt.edu/info/ai1.html.)

## E-mail Communication Policy

Each student is issued a University e-mail address (username@pitt.edu) upon admittance. This e-mail address may be used by the University for official communication with students. Students are expected to read e-mail sent to this account on a regular basis. Failure to read and react to University communications in a timely manner does not absolve the student from knowing and complying with the content of the communications. The University provides an e-mail forwarding service that allows students to read their e-mail via other service providers (e.g., Hotmail, AOL, Yahoo). Students that choose to forward their e-mail from their pitt.edu address to another address do so at their own risk. If e-mail is lost as a result of forwarding, it does not absolve the student from responding to official communications sent to their University e-mail address. To forward e-mail sent to your University account, go to http://accounts.pitt.edu, log into your account, click on Edit Forwarding Addresses, and follow the instructions on the page. Be sure to log out of your account when you have finished. (For the full E-mail Communication Policy, go to www.bc.pitt.edu/policies/policy/09/09-10-01.html.)

## Diversity and Inclusion

The University of Pittsburgh does not tolerate any form of discrimination,harassment, or retaliation based on disability, race, color, religion, national origin, ancestry, geneticinformation, marital status, familial status, sex, age, sexual orientation, veteran status or gender iden-tity or other factors as stated in the University’s Title IX policy. The University is committed to takingprompt action to end a hostile environment that interferes with the University’s mission. For moreinformation about policies, procedures, and practices, see: https://www.diversity.pitt.edu/about. I ask that everyone in the class strive to help ensure that other members of this class can learn in a support-ive and respectful environment. If there are instances of the aforementioned issues, please contact theTitle IX Coordinator, by calling 412-648-7860, or e-mailing titleixcoordinator@pitt.edu. Reports canalso be filed online: https://www.diversity.pitt.edu/civil-rights-title-ix-compliance/make-report.



