---
title: "Analysis of IR"
subtitle: "PS 1599 | Week 6: Demand failures"
institute: "University of Pittsburgh"
author: "Michaël Aklin"
format:
  revealjs:
    incremental: true
    theme: [white, revealjs_customization.scss]
    logo: materials/PASU_Logo.png
    center: true
    chalkboard: false
title-slide-attributes: 
    data-background-image: https://collectionapi.metmuseum.org/api/collection/v1/iiif/679844/1571243/main-image
    data-background-opacity: "0.4"
editor: visual
bibliography: /Users/AKLIN/Dropbox/BibLibrary.bib
---

## Administration

- Office hours

- aklin@pitt.edu 

- Updated schedule

- Slides

- Readings


##

::: {.r-fit-text}
What did we talk about last time?
:::

##

- In 'regular' times: mostly competition via prices and quality

- In times of disruptive tech: non-market strategies

- Two so far: [lobbying]{.blue} and [electing friendly pols]{.blue}

- Today:

  - Finish NMS

  - Start demand side issues

##

::: {.r-fit-text}
Is lobbying/influencing elections
:::

::: {.r-fit-text}
always a [bad]{.red} thing?
:::

##

- So far: lobbying = slow down transition = bad

- But: good reasons for gov intervention exist (and lobbying)!

- First: help innovation (already discussed)

- Second: lobbying helps provide information

- Third: address inequality between 'good' and 'bad' tech

## Bad tech lock-in

- Perfect market: superior tech replace inferior tech

- Market failures: problem of externalities

  - 'Good' tech produces [positive externalities]{.red}

  - 'Bad' tech produces [negative externalities]{.red}

- 'Good' tech cannot win alone **even** when it's socially desirable

- Example: [carbon lock-in]{.red}


::: footer
@Unruh2000, @Unruh2002
:::

<!-- ##

::: {.r-fit-text}
You work for the White House...
:::

::: {.r-fit-text}
Use your problem-solving skills
:::

::: {.r-fit-text}
to address the externalities asymmetry
::: -->

## Within markets 

- Next: within-markets NMS

- Note: not _exactly_ an NMS...

- But still about changing business environment


##  

- [Predatory pricing]{.red} and [dumping]{.red}

  - Idea: reduce price [below]{.blue} prod cost

  - Dumping: same but export

  - Makes it impossible to newcomers to compete

  - Example: Walmart. But: hard to prove

- Monopolistic acquisition(s): acquire/merge firm

- Capturing talent ([human capital]{.red})

  - Example: facebook and drop.io (Sam Lessin) 


<!-- ##

::: {.r-fit-text}
You work for a solar company.
:::

::: {.r-fit-text}
How would you push back against [lobbying]{.red} by coal companies?
:::

::: {.r-fit-text}
Use you problem-solving skills!
::: -->

<!-- ##

- Goal: make your firm robust to political turnover

- Problem: imbalance in lobbying power between you and fossil competition

- Strategies

  - Create a clean energy trade lobby (=pool resources)

  - Invest in fossil areas (=hard to overturn)

  - Support carbon tax? (Any risk it backfires?)

  - Others? -->


# Conclusion

##

- Price/product competition is good...

- Disruptive tech is a threat to firms

- Response is often: non-market strategies

- Some are 'good'! But many are 'bad'

- Threatens development

- What about _society_ NMS? Next topic!


# Demand-side failures

##

- Puzzle: why doesn't [new+better]{.blue} tech replace [old+bad]{.blue} tech?

- So far: supply-side explanations

  - Innovation failures

  - Diffusion failures

- Hidden assumption: people want new+better tech

- Is this true? [Demand-side]{.red} failures

## 

<!-- 
1. Preferences
2. 
3. Coordination problems -->

- [Demand-side]{.red} prob: issues with demand for 'good' tech

- Happens at three (four) levels:

  - Individual, household, social/community, (firms)

- The [calculus of demand]{.blue}

  - Benefits

  - Costs

  - Misc.

## Benefits

- Two types of goods/services:

  - Consumption goods

  - Investment goods

  - Some goods are both (eg internet)

- Key Q: what is the [utility]{.red} of acquiring a given tech?

  - At indiv level: benefits are about [taste]{.red}, [cultural pref]{.red}

  - At social level: B conditioned by [collective action issues]{.red}

## Problem

- Perfect market: supply responds to demand for new tech

- But we are interested in cases w/ [market failures]{.red}

- Prob for goods w/ [positive externalities]{.red} (not captured)

- [Private]{.red} benefits < [social]{.red} benefits

- Example: should I use an electric car or gasoline car?

- Right now: electric car ~$10k more than gasoline



## Costs

- Need to include the cons side

- Natural starting point: pecunary cost

- Other costs (symbolic, etc)

- Problem: [negative externalities]{.red} are not included!

- Thus: good tech might be overpriced and bad tech underpriced

##

::: {.r-fit-text}
How would you solve the pricing problem
::: 

::: {.r-fit-text}
of 'good' tech being [overpriced]{.red}...
::: 

::: {.r-fit-text}
and 'bad' tech being [underpriced]{.red}?
::: 

##

- Increase [private cost]{.red} of negative externalities
  
  - [Pigouvian]{.red} taxes

  - Trading systems. Eg EU ETS

  - Symbolic cost (eg fur)

- Increase [private benefit]{.red} of positive externalities

  - [Subsidies]{.red}. Eg tax credits

  - Symbolic gains (eg make green cool)

- [Which ones are politically more likely to work?]{.red}

## Misc

- Decision are never just a matter of money

  - Signaling, branding, etc

- Tech-specific issue: new products are unknown

  - [Unawareness]{.red}

  - [Uncertainty]{.red} regarding quality

- Example: solar technology in India

::: footer
@Aklinetal2018d
:::


## Household dynamics

- So far: discussion focused on [individuals]{.blue}

- But what about [households]{.blue}?

##

::: {.r-fit-text}
Can you think of reasons why moving from
::: 

::: {.r-fit-text}
[individuals]{.blue} to [households]{.blue}  
:::

::: {.r-fit-text}
could change the [decision calculus]{.blue}?
:::

##

- Decision-maker is not an individual '[rational]{.red}' actor

- Instead: [within-household bargaining]{.blue}

- Includes biases derived from econ and cultural factors

  - Who earns the money?

  - Who makes decisions about what?

  - Whose views carry more weight?

## Example: benefits of electricity access

- Context: India, >1b inhabitants, GDP/cap $2k

- But until ~2010: 700m w/o electricity

- Successful electrification programs (RGGVY, Saubhagya)

- Question: who benefited from electrification?

- Study conducted in rural northern India

- Answer: appliances by male head of HH (TV, non-kitchen fan, phone)

::: footer
@Rosenbergetal2019
:::

## Example (2): clean cook stoves

- Modern economies: use non-solid fuel (elec, gas)

- Poorer economies (~2.4b): solid fuel (wood, kerosene, charcoal, dung)

- Impact: indoor air pollution. [Who will be affected?]{.red}

- WHO: 3.2m deaths per year (2020); 237k children under 5

- Pulmonary diseases, lung cancer, breathing issues

<!-- Source: https://www.who.int/en/news-room/fact-sheets/detail/household-air-pollution-and-health -->


## Example (continued)

- [Solution]{.blue}: clean (or at least improved) cookstoves

- [Diagnostic]{.blue}: problem of cost (externalities) for HH and for countries

- [Solution]{.blue}: global funding effect led by Global Alliance for Clean Cookstoves (2010, Clinton)

- [Goal]{.blue}: replace solid-fuel cookstoves w/ clean ones (~100m units)

- In practice: distribution of 28m, seldom used

## Example (fin)


- Many problems...

- [Benefits]{.blue}: air pollution is not seen as a threat: awareness + intra-hh bargaining

- [Costs]{.blue}: good clean stoves are expensive

- Misc: clean cookstoves are often not designed in a way that matches traditional cooking styles

::: footer
@Mobaraketal2012
:::


# Conclusion

##

- 'Good' tech is often disadvantaged

- Problem of positive/negative [externalities]{.red}

- Good tech must be affordable!

- But not just about money: beliefs about problems, cultural values, etc. 

- Importance of social component in tech adoption

# Questions?

aklin@pitt.edu

<br>

<br>

<br>

<br>

<font size="5">Source for title page painting:  Joachim Beuckelaer, _Fish market_</font>

## References{.scrollable .smaller}
